Repository msamsami/fastapi-maintenance, pull requests merged in 2025-05, with the labels that each got.

#1 🐛 Fix Pydantic v2 raises `ImportError: cannot import name 'BoolError' from 'pydantic'`
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/question.yml
  .gitignore
  .python-version
  docs/release-notes.md
  src/fastapi_maintenance/__init__.py
  src/fastapi_maintenance/backends.py
Labels: bug

#2 🛠️ Add Dependabot configuration for package updates using `uv`
  .github/dependabot.yml
  docs/release-notes.md
Labels: documentation, internal

#3 📝 Improve clarity and organization of documentation
  README.md
  docs/index.md
  docs/release-notes.md
  docs/tutorial/context-manager.md
  docs/tutorial/index.md
  docs/tutorial/middleware-precedence.md
Labels: documentation

#4 🔧 Merge test dependencies into dev group and add Ruff linting configs
  docs/release-notes.md
  pyproject.toml
  uv.lock
Labels: internal, dependencies

#6 🔧 Make `_str_to_bool` method static in `BaseStateBackend` class
  docs/release-notes.md
  src/fastapi_maintenance/backends.py
Labels: internal

#8 📝 Fix incorrect references to “callback” instead of “handler” in docs
  docs/tutorial/advanced-usage.md
  docs/tutorial/custom-responses.md
Labels: documentation

#10 🐛 Fix bug: FastAPI documentation endpoints inaccessible during maintenance mode
  docs/tutorial/custom-exemptions.md
  pyproject.toml
  src/fastapi_maintenance/_handlers.py
  src/fastapi_maintenance/middleware.py
  tests/test_backends.py
  tests/test_middleware.py
Labels: bug, enhancement
